# Generated by Django 3.2.16 on 2022-10-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
        ('Courses', '0005_category_cat_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teachers.teacher'),
        ),
    ]
